//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarGuyGarage_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Availability
    {
        public int Id { get; set; }
        public int IdCompany { get; set; }
        public int IdCars { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Company Company { get; set; }
    }
}
